FROM python:3.8.0-slim

ADD . /code

RUN pip install poetry

WORKDIR /code

RUN poetry install

# we go with 1 worker number here as we have local cache
# if we want to improve the perf, we can simply scale up the replicas
CMD ["poetry", "run", "gunicorn", "-k", "gevent", "-w", "1", "-b", "0.0.0.0:8080", "app:app"]