apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"flask-node-log"},"name":"flask-node-log","namespace":"caas-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"flask-node-log"}},"strategy":{},"template":{"metadata":{"labels":{"app":"flask-node-log"}},"spec":{"containers":[{"image":"registry-jpe2-beta.r-local.net/caas-common/flask-app:v20221125-4","livenessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":30,"periodSeconds":10},"name":"flask-node-log","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"800m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"harbor-bot"}]}}}}
  creationTimestamp: "2022-11-25T09:12:59Z"
  generation: 17
  labels:
    app: flask-node-log
  name: flask-node-log
  namespace: caas-system
  resourceVersion: "2777888528"
  uid: 766d84e9-9f1b-4b2f-8f2b-49d64035d623
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-node-log
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-01-11T15:22:21+09:00"
      creationTimestamp: null
      labels:
        app: flask-node-log
        version: 2022-11-25-09.12.59
    spec:
      containers:
      - image: registry-jpe2-beta.r-local.net/caas-common/flask-node-log:v20230111
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 30s
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: flask-node-log
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: harbor-bot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-25T09:12:59Z"
    lastUpdateTime: "2023-01-11T09:28:08Z"
    message: ReplicaSet "flask-node-log-85dff9946d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-01-11T09:44:55Z"
    lastUpdateTime: "2023-01-11T09:44:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
