apiVersion: v1
kind: Service
metadata:
  name: flask-node-log-svc
  namespace: caas-system
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  selector:
    app: flask-node-log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-node-log
  name: flask-node-log
  namespace: caas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-node-log
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-node-log
    spec:
      containers:
      - image: registry-jpe2-beta.r-local.net/caas-common/flask-node-log:test
        name: flask-node-log
        env:
          - name: CLIENT_SECRET_QA
            valueFrom:
              secretKeyRef:
                name: client-k8s-credentials
                key: client_secret_qa
          - name: CLIENT_SECRET_PROD
            valueFrom:
              secretKeyRef:
                name: client-k8s-credentials
                key: client_secret_prod
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "800m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: harbor-bot
      dnsPolicy: ClusterFirst
